about_widget_content = "Let's build a safer cyberspace together!"
address = ""
author = "Lickos"
categories_title = "Blog Categories"
contact_form_action = "#"
copyright = "Copyright by Lickyber Tech"
custom_script = ""
description = "Lickos Adventures in CyberSpace...."
email = "ma@lickyber.tech"
error_404_button = "Back To Home"
error_404_text = "404 Page Not Found!"
favicon = "images/favicon.png"
featured_post_button = "Featured"
featured_post_title = "Featured Post"
footer_content = "Innovation | CyberSecurity | Technology | Project Management | Community"
logo = "images/lick-av.jpg"
logo_text = "Blog :: Lickyber Tech"
logo_width = "150x"
mainSections = ["blog"]
mobile = ""
navbar_fixed = false
next_button = "Next"
no_categories_found = "No Categories Found"
no_tags_found = "No Tags Found"
posts_title = "Featured"
previous_button = "Previous"
read_more_button = "Read more"
recent_post_button = "Recent"
recent_post_title = "Recent Post"
related_posts = "Related Posts"
search = true
showing_posts = "Showing Post From"
theme_copyright = true
[advertisement]
image = "images/promotion.png"
link = "https://gethugothemes.com/"
[banner]
background_image = "/images/banner-bg-shape.svg"
button_label = "Know About Me"
button_link = "about/"
content = "CyberSecurity and Project Management are what drives me and I aspire to become a Research Manager.."
enable = true
image = "images/banner.png"
title_large = "Welcome **!**"
title_small = "to Lickos Blog"
[cookies]
button = "I Accept"
content = "This site uses cookies. By continuing to use this website, you agree to their use."
enable = true
expire_days = 2
[preloader]
enable = false
preloader = ""
[subscription]
enable = false
mailchimp_form_action = "https://gmail.us4.list-manage.com/subscribe/post?u=463ee871f45d2d93748e77cad&amp;id=a0a2c6d074"
mailchimp_form_name = "b_463ee871f45d2d93748e77cad_a0a2c6d074"
newsletter_button = "Sign in"
newsletter_invitation = "Join thousands of Tiny Salt subscribers and get our best recipes delivered each week!"
newsletter_placeholder = "Type And Hit Enter"
newsletter_reminder_a = "By Singing Up, You Agree To"
newsletter_reminder_b = "Privacy Policy"
newsletter_title = "Newsletter"
[widgets]
sidebar = ["about", "recent-post", "newsletter"]
[[social]]
icon = "fab fa-twitter"
link = "https://twitter.com/LickosA"
title = "twitter"
[[social]]
icon = "fab fa-instagram"
link = "https://www.instagram.com/koupam.alassane/"
title = "instagram"
[[social]]
icon = "fab fa-github"
link = "github.com/LickosA"
title = "github"
[[social]]
icon = "fab fa-linkedin"
link = "https://www.linkedin.com/in/malick-k-alassane/"
title = "linkedin"
